// <auto-generated />
using Cars.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cars.API.Migrations
{
    [DbContext(typeof(CarsContext))]
    partial class CarsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Cars.API.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Toyota",
                            Color = "Red",
                            Model = "Camry",
                            VIN = "1HGBH41JXMN109186",
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Ford",
                            Color = "Blue",
                            Model = "Mustang",
                            VIN = "1HGBH41JXMN109187",
                            Year = 2021
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Chevrolet",
                            Color = "Black",
                            Model = "Camaro",
                            VIN = "1HGBH41JXMN109188",
                            Year = 2019
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Tesla",
                            Color = "White",
                            Model = "Model S",
                            VIN = "1HGBH41JXMN109189",
                            Year = 2022
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Nissan",
                            Color = "Grey",
                            Model = "Altima",
                            VIN = "1HGBH41JXMN109190",
                            Year = 2018
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Honda",
                            Color = "Silver",
                            Model = "Civic",
                            VIN = "1HGBH41JXMN109191",
                            Year = 2020
                        },
                        new
                        {
                            Id = 7,
                            Brand = "BMW",
                            Color = "Blue",
                            Model = "3 Series",
                            VIN = "1HGBH41JXMN109192",
                            Year = 2021
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Audi",
                            Color = "White",
                            Model = "A4",
                            VIN = "1HGBH41JXMN109193",
                            Year = 2019
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Mercedes-Benz",
                            Color = "Black",
                            Model = "C-Class",
                            VIN = "1HGBH41JXMN109194",
                            Year = 2022
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Volkswagen",
                            Color = "Red",
                            Model = "Golf",
                            VIN = "1HGBH41JXMN109195",
                            Year = 2018
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
